import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:nfw/models/workout_intensity.dart';
import 'package:nfw/screens/home_screen.dart';
import 'package:nfw/services/workout_service.dart';
import 'package:provider/provider.dart';
import 'package:mockito/annotations.dart';

// Generate mock for WorkoutService
@GenerateMocks([WorkoutService])
import 'home_screen_test.mocks.dart'; // This file will be generated by build_runner

void main() {
  group('HomeScreen', () {
    late MockWorkoutService mockWorkoutService;

    setUp(() {
      mockWorkoutService = MockWorkoutService();
      // Default stubbing for common getters
      when(mockWorkoutService.isWorkoutActive).thenReturn(false);
      when(mockWorkoutService.remainingTime).thenReturn(Duration.zero);
      when(mockWorkoutService.workoutIntensity).thenReturn(null);
    });

    Widget createHomeScreen() {
      return MaterialApp(
        home: ChangeNotifierProvider<WorkoutService>.value(
          value: mockWorkoutService,
          child: const HomeScreen(),
        ),
      );
    }

    testWidgets('displays initial state when workout is not active', (
      tester,
    ) async {
      await tester.pumpWidget(createHomeScreen());

      expect(find.text('Ready to workout?'), findsOneWidget);
      expect(find.text('00:00'), findsOneWidget);
      expect(find.text('Start Workout'), findsOneWidget);
      expect(find.text('Recommended intake:'), findsNothing);
      expect(find.byType(Image), findsNothing);
    });

    testWidgets('displays active state with normal intensity', (tester) async {
      when(mockWorkoutService.isWorkoutActive).thenReturn(true);
      when(
        mockWorkoutService.remainingTime,
      ).thenReturn(const Duration(minutes: 14, seconds: 59));
      when(
        mockWorkoutService.workoutIntensity,
      ).thenReturn(WorkoutIntensity.normal);

      await tester.pumpWidget(createHomeScreen());
      await tester.pumpAndSettle(); // Allow UI to update

      expect(find.text('Next reminder in:'), findsOneWidget);
      expect(find.text('14:59'), findsOneWidget);
      expect(find.text('End Workout'), findsOneWidget);
      expect(find.text('Recommended intake:'), findsOneWidget);
      expect(find.byType(Image), findsOneWidget); // One bottle for normal
    });

    testWidgets('displays active state with heavy intensity', (tester) async {
      when(mockWorkoutService.isWorkoutActive).thenReturn(true);
      when(
        mockWorkoutService.remainingTime,
      ).thenReturn(const Duration(minutes: 19, seconds: 30));
      when(
        mockWorkoutService.workoutIntensity,
      ).thenReturn(WorkoutIntensity.heavy);

      await tester.pumpWidget(createHomeScreen());
      await tester.pumpAndSettle(); // Allow UI to update

      expect(find.text('Next reminder in:'), findsOneWidget);
      expect(find.text('19:30'), findsOneWidget);
      expect(find.text('End Workout'), findsOneWidget);
      expect(find.text('Recommended intake:'), findsOneWidget);
      expect(find.byType(Image), findsNWidgets(2)); // Two bottles for heavy
    });

    testWidgets('calls startWorkout when Start Workout button is tapped', (
      tester,
    ) async {
      await tester.pumpWidget(createHomeScreen());
      await tester.tap(find.text('Start Workout'));
      verify(mockWorkoutService.startWorkout()).called(1);
    });

    testWidgets('calls stopWorkout when End Workout button is tapped', (
      tester,
    ) async {
      when(mockWorkoutService.isWorkoutActive).thenReturn(true);
      await tester.pumpWidget(createHomeScreen());
      await tester.tap(find.text('End Workout'));
      verify(mockWorkoutService.stopWorkout()).called(1);
    });
  });
}
